import cron from "node-cron";
import { cityClassificationQueue } from "../config/Queues.js";
import Order from "../models/Order.js";
import CityMetadata from "../models/CityMetadata.js";
import Brand from "../models/Brands.js";
import LocationAdSpend from "../models/LocationAdSpend.js";
import { syncAllLocationSpend } from "../services/locationSpendService.js";
export const setupLocationClassificationCron = () => {
  cron.schedule(
    "0 6 * * *",
    async () => {
      console.log("🔄 [Cron] Starting daily city classification job...");

      try {
        const now = new Date();
        const yesterdayStart = new Date(now);
        yesterdayStart.setDate(yesterdayStart.getDate() - 1);
        yesterdayStart.setHours(0, 0, 0, 0);

        const yesterdayEnd = new Date(now);
        yesterdayEnd.setDate(yesterdayEnd.getDate() - 1);
        yesterdayEnd.setHours(23, 59, 59, 999);

        console.log(
          `📅 [Cron] Checking orders from ${yesterdayStart.toISOString()} to ${yesterdayEnd.toISOString()} (yesterday only)`,
        );

        const unknownCities = await Order.aggregate([
          {
            $match: {
              orderCreatedAt: {
                $gte: yesterdayStart,
                $lte: yesterdayEnd,
              },
              city: { $exists: true, $ne: null, $nin: [null, ""] },
              state: { $exists: true, $ne: null, $nin: [null, ""] },
            },
          },
          {
            $group: {
              _id: {
                city: { $toLower: { $trim: { input: "$city" } } },
                state: { $toLower: { $trim: { input: "$state" } } },
              },
              originalCity: { $first: "$city" },
              originalState: { $first: "$state" },
            },
          },
          {
            $project: {
              _id: 0,
              cityNormalized: "$_id.city",
              city: "$originalCity",
              state: "$originalState",
              // Note: lookupKey will be generated by GPT/worker with country
            },
          },
        ]);

        if (unknownCities.length === 0) {
          console.log("✅ [Cron] No cities found in yesterday's orders");
          return;
        }

        console.log(
          `📊 [Cron] Found ${unknownCities.length} unique city/state combinations from yesterday`,
        );

        // 2. Check which cities are already in CityMetadata (match on city+state since country is dynamic)
        // Use aggregation to efficiently get unique city+state combinations
        const existing = await CityMetadata.aggregate([
          {
            $group: {
              _id: {
                cityNormalized: { $toLower: "$cityNormalized" },
                state: { $toLower: "$state" },
              },
            },
          },
          {
            $project: {
              _id: 0,
              key: {
                $concat: ["$_id.cityNormalized", "_", "$_id.state"],
              },
            },
          },
        ]);

        const existingCityStateSet = new Set(existing.map((c) => c.key));

        // 3. Filter out already classified cities
        const newCities = unknownCities.filter((c) => {
          const cityStateKey = `${c.cityNormalized}_${(c.state || "").toLowerCase().trim()}`;
          return !existingCityStateSet.has(cityStateKey);
        });

        if (newCities.length === 0) {
          console.log("✅ [Cron] All cities already classified");
          return;
        }

        console.log(
          `🆕 [Cron] Found ${newCities.length} new cities to classify`,
        );

        // 4. Batch cities (20 per GPT call)
        const batchSize = 20;
        const batches = [];

        for (let i = 0; i < newCities.length; i += batchSize) {
          batches.push(newCities.slice(i, i + batchSize));
        }

        console.log(`📦 [Cron] Creating ${batches.length} batch jobs`);

        // 5. Queue batch jobs
        const jobPromises = batches.map((batch, index) => {
          return cityClassificationQueue.add(
            "classify-cities-batch",
            {
              type: "batch",
              cities: batch,
              batchNumber: index + 1,
              totalBatches: batches.length,
            },
            {
              priority: 1, // Normal priority for cron jobs
              attempts: 3,
              backoff: {
                type: "exponential",
                delay: 2000,
              },
            },
          );
        });

        await Promise.all(jobPromises);

        console.log(
          `✅ [Cron] Queued ${batches.length} batch jobs for city classification`,
        );
      } catch (error) {
        console.error("❌ [Cron] Error in city classification job:", error);
      }
    },
    { timezone: "Asia/Kolkata" },
  );

  console.log("✅ [Cron] Daily city classification cron scheduled (6 AM IST)");

  // New Cron for Daily Ad Spend Sync (Self-Healing)
  cron.schedule(
    "30 5 * * *",
    async () => {
      console.log("🔄 [Cron] Starting daily Location Ad Spend sync job...");
      try {
        const brands = await Brand.find({
          $or: [
            { fbAccessToken: { $exists: true, $ne: null } },
            { googleAdsRefreshToken: { $exists: true, $ne: null } },
          ],
        });

        console.log(`📊 [Cron] Found ${brands.length} brands to sync spend for`);

        const now = new Date();
        const yesterdayEnd = new Date(now);
        yesterdayEnd.setDate(yesterdayEnd.getDate() - 1);
        yesterdayEnd.setHours(23, 59, 59, 999);

        // Self-Healing Logic: Check the last date synced in DB
        for (const brand of brands) {
          try {
            // Find the most recent date we have data for
            const lastRecord = await LocationAdSpend.findOne({ brandId: brand._id })
              .sort({ date: -1 })
              .lean();

            let startDate;
            if (lastRecord && lastRecord.date) {
               // Start from the day after the last recorded date
               startDate = new Date(lastRecord.date);
               startDate.setDate(startDate.getDate() + 1);
               startDate.setHours(0, 0, 0, 0);
            } else {
               // Fallback to yesterday if no data exists
               startDate = new Date(now);
               startDate.setDate(startDate.getDate() - 1);
               startDate.setHours(0, 0, 0, 0);
            }

            // If startDate is somehow in the future or after yesterdayEnd, skip or sync just yesterday
            if (startDate > yesterdayEnd) {
                console.log(`✅ [Cron] Brand ${brand.name} is already up to date.`);
                continue;
            }

            console.log(`⏳ [Cron] Syncing brand ${brand.name} from ${startDate.toISOString().split('T')[0]} to ${yesterdayEnd.toISOString().split('T')[0]}`);
            
            await syncAllLocationSpend(brand._id, startDate, yesterdayEnd);
            console.log(`✅ [Cron] Synced spend for brand ${brand.name}`);
          } catch (err) {
            console.error(`❌ [Cron] Error syncing spend for brand ${brand.name}:`, err);
          }
        }
        console.log("✅ [Cron] Daily Location Ad Spend sync complete.");
      } catch (error) {
        console.error("❌ [Cron] Error in Location Ad Spend sync job:", error);
      }
    },
    { timezone: "Asia/Kolkata" },
  );

  console.log("✅ [Cron] Daily Location Ad Spend sync scheduled (5:30 AM IST)");
};
